name: Update rules index

on:
  push:
    paths:
      - 'rules/01_工资模块_latest.md'
  release:
    types: [published]
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Ensure UTF-8
        run: |
          echo "LANG=C.UTF-8" >> $GITHUB_ENV
          echo "LC_ALL=C.UTF-8" >> $GITHUB_ENV

      - name: Read version from latest (识别可选 -HFx)
        id: v
        shell: bash
        run: |
          set -euo pipefail
          latest="rules/01_工资模块_latest.md"
          # 兼容：`版本 vYYYY-MM-DDR7` 或 `版本 vYYYY-MM-DDR7-HF2`（全/半角冒号都行）
          ver=$(grep -E -m1 '^版本[ ：:]*v[0-9-]+R[0-9A-Za-z]+(-HF[0-9]+)?' "$latest" \
                | sed -E 's/.*(v[0-9-]+R[0-9A-Za-z]+(-HF[0-9]+)?).*/\1/')
          if [ -z "${ver:-}" ]; then
            echo "❌ 未在 latest 中解析到版本号" >&2
            exit 1
          fi
          echo "ver=$ver" >> "$GITHUB_OUTPUT"

      - name: Patch rules/README.md（版本与实体都更新，支持 -HFx）
        id: patch
        shell: bash
        run: |
          set -euo pipefail
          v='${{ steps.v.outputs.ver }}'
          readme="rules/README.md"

          # 1) “当前生效版本”行：01_工资模块 → vXXXX
          sed -i -E "s/(01_工资模块[[:space:]]*→[[:space:]]*)v[0-9-]+R[0-9A-Za-z]+(-HF[0-9]+)?/\\1${v}/" "$readme"

          # 2) 实体链接：./01_工资模块_vXXXX.md
          sed -i -E "s#\\(\\./01_工资模块_v[0-9-]+R[0-9A-Za-z]+(-HF[0-9]+)?\\.md\\)#(./01_工资模块_${v}.md)#" "$readme"

          # 记录是否有变更
          if git diff --exit-code -- "$readme" > /dev/null; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      # 改为走 PR：固定 ASCII 分支名，避免全角/隐藏字符
      - name: Create or Update Pull Request
        if: steps.patch.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: chore/bump-rules-index
          base: main
          title: "docs(rules): bump index to ${{ steps.v.outputs.ver }}"
          commit-message: "docs(rules): bump index to ${{ steps.v.outputs.ver }}"
          body: |
            自动更新规则索引：
            - 当前生效版本：${{ steps.v.outputs.ver }}
            - 实体：`01_工资模块_${{ steps.v.outputs.ver }}.md`
            由工作流触发（push/release/手动）。
          labels: rules-index, bot
          signoff: false
          delete-branch: true

      # 可选：若仓库已开启“自动合并”，则自动合并该 PR
      - name: Enable auto-merge (optional)
        if: steps.patch.outputs.changed == 'true'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.create_pull_request.outputs.pull-request-number }}
          merge-method: squash
